services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  solarwatch:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=solarwatch;Username=postgres;Password=postgres
      - OpenWeather__ApiKey=90f4e53ec2c66ac306de8e41af3e6ecb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
